objects/Media_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Media Buckets</relationshipLabel>
        <relationshipName>Media_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Bucket</label>
    <nameField>
        <label>Media Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Media_Bucket_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Media_Bucket__c</fullName>
        <label>Media Bucket</label>
        <referenceTo>Media_Bucket__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Media_Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Discount</label>
        <referenceTo>Media_Discount__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Media_Product__c</fullName>
        <label>Media Product</label>
        <referenceTo>Media_Product__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Bucket Item</label>
    <nameField>
        <displayFormat>BUCKET_I-{0000000}</displayFormat>
        <label>Media Bucket Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Bucket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Media_Discount__c.object
<CustomObject>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Media Discount</label>
    <nameField>
        <label>Media Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Media_Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Media Product</label>
    <nameField>
        <label>Media Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MediaStoreHelper.cls
public class MediaStoreHelper {
	public MediaStoreHelper () {}
	
	public static void updateMediaBucketItemPrice(List<Media_Bucket_Item__c> bucketItems) {
		for (Media_Bucket_Item__c record : bucketItems) {
			if (record.Media_Discount__c != null) {
				if (record.Media_Discount__r.Percent__c != null) {
					record.Cost__c = record.Media_Product__r.Price__c * (1 - record.Media_Discount__r.Percent__c / 100);
				}
				else if (record.Media_Discount__r.Value__c != null) {
					record.Cost__c = record.Media_Product__r.Price__c - record.Media_Discount__r.Value__c;
				}
			}
			else {
				record.Cost__c = record.Media_Product__r.Price__c;
			}
		}
		update bucketItems;
	}
	
	public static List<Media_Bucket_Item__c> getMediaBucketItemList(Set<Id> itemIds, Set<Id> productsIds) {
		List<Media_Bucket_Item__c> bucketItems = [
			SELECT Id,
				Media_Discount__c,
				Media_Discount__r.Value__c,
				Media_Discount__r.Percent__c,
				Media_Product__c,
				Media_Product__r.Price__c,
				Cost__c
			FROM Media_Bucket_Item__c
			WHERE Id IN :itemIds
				OR Media_Product__c IN :productsIds
		];
		return bucketItems;
	}

	public static Id getCurrentBucketId() {
		User currentUser = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
		String contactId = currentUser.ContactId;
		Media_Bucket__c bucket = [SELECT Id FROM Media_Bucket__c WHERE Contact__c = :contactId];
		return bucket != null ? bucket.Id : null;
	}
}