objects/Media_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Media Buckets</relationshipLabel>
        <relationshipName>Media_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Bucket</label>
    <nameField>
        <label>Media Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Media_Bucket_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Media_Bucket__c</fullName>
        <label>Media Bucket</label>
        <referenceTo>Media_Bucket__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Media_Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Discount</label>
        <referenceTo>Media_Discount__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Media_Product__c</fullName>
        <label>Media Product</label>
        <referenceTo>Media_Product__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Bucket Item</label>
    <nameField>
        <displayFormat>BUCKET_I-{0000000}</displayFormat>
        <label>Media Bucket Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Bucket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Media_Discount__c.object
<CustomObject>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Media Discount</label>
    <nameField>
        <label>Media Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Media_Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Media Product</label>
    <nameField>
        <label>Media Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TriggerTest.cls
@isTest
private class TriggerTest {

	private static testMethod void test() 
	{
        Contact customer = new Contact
        (
            FirstName = 'Test',
            LastName = 'Test'
        );
        insert customer;
            
        Media_Bucket__c bucket = new Media_Bucket__c
        (
            Contact__c = customer.Id,
            Name = 'Test Bucket'
        );
        insert bucket;
        
        Media_Product__c product = new Media_Product__c
        (
            Price__c = 100,
            Description__c = 'blabla',
            Name = 'Test Product'
        );
        insert product;
        
        Media_Discount__c percentDiscount = new Media_Discount__c
        (
            Percent__c = 10,
            Name = 'Test pd'
        );
        insert percentDiscount;
        
        Media_Discount__c valueDiscount = new Media_Discount__c
        (
            Value__c = 2,
            Name = 'Test vd'
        );
        insert valueDiscount;
                
        Test.startTest();
        
        Media_Bucket_Item__c bi = new Media_Bucket_Item__c
        (
            Media_Product__c = product.Id,
            Media_Discount__c = percentDiscount.Id,
            Media_Bucket__c = bucket.Id
        );
        insert bi;
        
        bi = [SELECT Id,Media_Discount__c, Cost__c FROM Media_Bucket_Item__c WHERE Id = : bi.Id];
        System.assert(bi.Cost__c == 90);
        
        Test.stopTest();
	}

}