objects/Media_Bucket_Item__c.object
<CustomObject>
    <fields>
        <fullName>Media_Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Discount</label>
        <referenceTo>Media_Discount__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Bucket Item</label>
    <nameField>
        <displayFormat>BUCKET_I-{0000000}</displayFormat>
        <label>Media Bucket Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Bucket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Media_Discount__c.object
<CustomObject>
    <label>Media Discount</label>
    <nameField>
        <label>Media Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CalculateCostValueTriggerHandler.cls
public class CalculateCostValueTriggerHandler {

	public static void process(List<Media_Bucket_Item__c> records, Map<Id, Media_Bucket_Item__c> oldMap, Boolean isInsert) {

		Set<Id> buketItemIds = new Set<Id>();
		for (Media_Bucket_Item__c record : records) {
			if (isInsert || record.Media_Discount__c != oldMap.get(record.Id).Media_Discount__c) {
				buketItemIds.add(record.Id);
			}
		}
		List<Media_Bucket_Item__c> bucketItems = MediaStoreHelper.getMediaBucketItemList(buketItemIds, null);
	
		MediaStoreHelper.updateMediaBucketItemPrice(bucketItems);
	}
}