objects/Media_Bucket_Item__c.object
<CustomObject>
    <fields>
        <fullName>Media_Product__c</fullName>
        <label>Media Product</label>
        <referenceTo>Media_Product__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Bucket Item</label>
    <nameField>
        <displayFormat>BUCKET_I-{0000000}</displayFormat>
        <label>Media Bucket Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Bucket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Media_Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Media Product</label>
    <nameField>
        <label>Media Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateBucketItemCostTriggerHandler.cls
public class UpdateBucketItemCostTriggerHandler {


	public static void process(List<Media_Product__c> records, Map<Id, Media_Product__c> oldMap) {
		Set<Id> productsIds = new Set<Id>();
		for (Media_Product__c record : records) {
			if (record.Price__c != oldMap.get(record.Id).Price__c) {
				productsIds.add(record.Id);
			}
		}

		List<Media_Bucket_Item__c> bucketItems = MediaStoreHelper.getMediaBucketItemList(null, productsIds);
		MediaStoreHelper.updateMediaBucketItemPrice(bucketItems);
	}
}