objects/Media_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Media Buckets</relationshipLabel>
        <relationshipName>Media_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Bucket</label>
    <nameField>
        <label>Media Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Media_Bucket_Item__c.object
<CustomObject>
    <fields>
        <fullName>Media_Bucket__c</fullName>
        <label>Media Bucket</label>
        <referenceTo>Media_Bucket__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Media_Product__c</fullName>
        <label>Media Product</label>
        <referenceTo>Media_Product__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Bucket Item</label>
    <nameField>
        <displayFormat>BUCKET_I-{0000000}</displayFormat>
        <label>Media Bucket Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Bucket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Media_Order__c.object
<CustomObject>
    <fields>
        <fullName>Media_Bucket__c</fullName>
        <label>Media Bucket</label>
        <referenceTo>Media_Bucket__c</referenceTo>
        <relationshipLabel>Media Orders</relationshipLabel>
        <relationshipName>Media_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Order</label>
    <nameField>
        <label>Media Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Media_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Media_Order__c</fullName>
        <label>Media Order</label>
        <referenceTo>Media_Order__c</referenceTo>
        <relationshipLabel>Media Order Items</relationshipLabel>
        <relationshipName>Media_Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Media_Product__c</fullName>
        <label>Media Product</label>
        <referenceTo>Media_Product__c</referenceTo>
        <relationshipLabel>Media Order Items</relationshipLabel>
        <relationshipName>Media_Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Order Item</label>
    <nameField>
        <displayFormat>ORDER_I-{0000000}</displayFormat>
        <label>Media Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Media_Product__c.object
<CustomObject>
    <fields>
        <fullName>Access_Link__c</fullName>
        <label>Access Link</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>10</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Game</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Movie</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Media Product</label>
    <nameField>
        <label>Media Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Media_Store_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Product_Page_Size__c</fullName>
        <label>Product Page Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Store Setting</label>
</CustomObject>

classes/MediaStoreController.cls
public with sharing class MediaStoreController {
	
	

	public List<ProductWrapper> productWrapperList { get; set; }
	private Id currentContactId { get; set; }

	public Integer getBucketSize() {
		return [SELECT COUNT() FROM Media_Bucket_Item__c WHERE Media_Bucket__r.Contact__c = :currentContactId];
	}

	public MediaStoreController() {
	    Integer pageSize = Integer.valueOf(Media_Store_Setting__c.getInstance().Product_Page_Size__c);
		List<Media_Product__c> products = [
			SELECT Id,
				Name,
				Description__c,
				Price__c,
				Rating__c,
				Type__c,
				Access_Link__c,
				(SELECT Id, Name FROM Attachments ORDER BY LastModifiedDate DESC LIMIT 1)
			FROM Media_Product__c
			ORDER BY CreatedDate DESC
			LIMIT :pageSize
		];

		productWrapperList = new List<ProductWrapper>();

		User currentUser = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
		currentContactId = currentUser.ContactId;

		List<Media_Bucket_Item__c> bucketItemList = [
			SELECT Id,
				Media_Product__c
			FROM Media_Bucket_Item__c
			WHERE Media_Bucket__r.Contact__c = :currentContactId
		];

		Map<Id, Id> bucketMap = new Map<Id, Id>();
		for (Media_Bucket_Item__c item : bucketItemList) {
			bucketMap.put(item.Media_Product__c, item.Id);
		}

		List<Media_Order_Item__c> orderItemList = [
			SELECT Id,
			Media_Product__c
			FROM Media_Order_Item__c
			WHERE Media_Order__r.Media_Bucket__r.Contact__c = :currentContactId
		];

		Set<Id> checkProductInOrder = new Set<Id>();
		for (Media_Order_Item__c item : orderItemList) {
			checkProductInOrder.add(item.Media_Product__c);
		}

		for (Media_Product__c product : products) {
			productWrapperList.add(
				new ProductWrapper(
					product,
					bucketMap.containsKey(product.Id),
					checkProductInOrder.contains(product.Id),
					bucketMap.containsKey(product.Id) ? bucketMap.get(product.Id) : null
				)
			);
		}
	}

}