objects/Media_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Media Buckets</relationshipLabel>
        <relationshipName>Media_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Bucket</label>
    <nameField>
        <label>Media Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Media_Bucket_Item__c.object
<CustomObject>
    <fields>
        <fullName>Media_Bucket__c</fullName>
        <label>Media Bucket</label>
        <referenceTo>Media_Bucket__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Media_Product__c</fullName>
        <label>Media Product</label>
        <referenceTo>Media_Product__c</referenceTo>
        <relationshipLabel>Media Bucket Items</relationshipLabel>
        <relationshipName>Media_Bucket_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Bucket Item</label>
    <nameField>
        <displayFormat>BUCKET_I-{0000000}</displayFormat>
        <label>Media Bucket Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Bucket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Media_Product__c.object
<CustomObject>
    <fields>
        <fullName>Access_Link__c</fullName>
        <label>Access Link</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>10</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Game</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Movie</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Media Product</label>
    <nameField>
        <label>Media Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProductWrapper.cls
public class ProductWrapper {

	public Id detailId { get; set; }
	public Id bucketItemId { get; set; }
	public String name { get; set; }
	public String description { get; set; }
	public String type { get; set; }
	public Double price { get; set; }
	public Double rating { get; set; }
	public Id attachmentId { get; set; }
	public Boolean isPreOrdered { get; set; }
	public Boolean isOrdered { get; set; }
	public String accessLink { get; set; }
	

	public Boolean getIsShow() {
		return attachmentId != null;
	}

	public ProductWrapper() {

	}

	public ProductWrapper(Media_Product__c product, Boolean preOrdered, Boolean ordered, Id inBucketItemId) {
		detailId = product.Id;
		name = product.Name;
		description = product.Description__c;
		type = product.Type__c;
		price = product.Price__c;
		rating = product.Rating__c;
		attachmentId = product.Attachments.isEmpty() == false ? product.Attachments[0].Id : null;
		isPreOrdered = preOrdered;
		isOrdered = ordered;
		bucketItemId = inBucketItemId;
		accessLink = product.Access_Link__c;
	}

	public void add() {
		if (isPreOrdered == false && isOrdered == false) {
			User currentUser = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
			String contactId = currentUser.ContactId;
			Media_Bucket__c bucket = [SELECT Id FROM Media_Bucket__c WHERE Contact__c = :contactId LIMIT 1];
			if (bucket != null) {
				Media_Bucket_Item__c bucketItem = new Media_Bucket_Item__c(
					Media_Product__c = detailId,
					Media_Bucket__c = bucket.Id
				);
				insert bucketItem;
				isPreOrdered = true;
				bucketItemId = bucketItem.Id;
			}
		}
	}

	public void remove() {
		if (isPreOrdered && bucketItemId != null) {
			delete [SELECT Id FROM Media_Bucket_Item__c WHERE Id = :bucketItemId];
			isPreOrdered = false;
			bucketItemId = null;
		}
	}
}