objects/Pizza__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pizza</relationshipLabel>
        <relationshipName>Pizza</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pizza</label>
    <nameField>
        <label>Pizza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Base__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Base</label>
    <nameField>
        <label>Pizza Base Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Bases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Order__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <summarizedField>Pizza_Order_Item__c.Cost__c</summarizedField>
        <summaryForeignKey>Pizza_Order_Item__c.Pizza_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pizza_Orders</relationshipLabel>
        <relationshipName>Pizza_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pizza_Order</label>
    <nameField>
        <displayFormat>Order_I-{0000000}</displayFormat>
        <label>Pizza Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pizza_Base__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pizza_Base</label>
        <referenceTo>Pizza_Base__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pizza_Order__c</fullName>
        <label>Pizza_Order</label>
        <referenceTo>Pizza_Order__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Order_Item</label>
    <nameField>
        <displayFormat>ORDER_ITEM_I-{0000000}</displayFormat>
        <label>Pizza Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Order_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CalculateOrderItemCostTriggerHandlerTest.cls
@isTest
private class CalculateOrderItemCostTriggerHandlerTest {

	@isTest static void test_method_one() {
		Contact customer = new Contact(
			FirstName = 'Test',
			LastName = 'Test'
		);
		insert customer;

		Pizza__c pizza = new Pizza__c(
			Cost__c = 5,
			Name = 'Test pizza'
		);
		insert pizza;
		
		Pizza__c pizza2 = new Pizza__c(
			Cost__c = 10,
			Name = 'Test pizza2'
		);
		insert pizza2;

		Pizza_Base__c base = new Pizza_Base__c(
			Cost__c = 1,
			Name = 'Test base'
		);
		insert base;

		Pizza_Order__c testOrder = new Pizza_Order__c(
			Customer__c = customer.Id
		);
		insert testOrder;
        
        
		Test.startTest();

		Pizza_Order_Item__c orderItem1 = new Pizza_Order_Item__c(
			Pizza__c = pizza.Id,
			Pizza_Base__c = base.Id,
			Pizza_Order__c = testOrder.Id,
			Count__c = 1
		);
		insert orderItem1;
		
		Pizza_Order_Item__c orderItem2 = new Pizza_Order_Item__c(
			Pizza__c = pizza2.Id,
			Pizza_Base__c = base.Id,
			Pizza_Order__c = testOrder.Id,
			Count__c = 1
		);
		insert orderItem2;
		Pizza_Order__c temp = [SELECT Id,  Cost__c FROM Pizza_Order__c WHERE Id = :testOrder.Id];
		System.assert(temp.Cost__c == 17);

		

		Test.stopTest();
	}

}