objects/Pizza__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza</label>
    <nameField>
        <label>Pizza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Ingredient</label>
    <nameField>
        <label>Pizza Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient_Item__c.object
<CustomObject>
    <fields>
        <fullName>Pizza_Ingredient__c</fullName>
        <label>Pizza_Ingredient</label>
        <referenceTo>Pizza_Ingredient__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Ingredient_Item</label>
    <nameField>
        <displayFormat>Ingredient_I-{0000000}</displayFormat>
        <label>Pizza Ingredient Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Ingredient_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateIngredientCostTriggerHandler.cls
public class UpdateIngredientCostTriggerHandler {
    public static void process(List<Pizza_Ingredient__c> records,Map<Id,Pizza_Ingredient__c> oldMap) {
        for(Pizza_Ingredient__c item : records)
        {
            List<Pizza_Ingredient_Item__c> temp = [SELECT Id, Pizza__c FROM Pizza_Ingredient_Item__c WHERE Pizza_Ingredient__c = :item.Id];
            for(Pizza_Ingredient_Item__c ingItem : temp)
            {
                Pizza__c pizza = [SELECT Id,Cost__c FROM Pizza__c WHERE Id = :ingItem.Pizza__c];
                pizza.Cost__c -= oldMap.get(item.Id).Cost__c;
                pizza.Cost__c += item.Cost__c;
                update pizza;
            }
        }
    }
}