objects/Pizza__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza</label>
    <nameField>
        <label>Pizza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Base__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Base</label>
    <nameField>
        <label>Pizza Base Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Bases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pizza_Base__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pizza_Base</label>
        <referenceTo>Pizza_Base__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Order_Item</label>
    <nameField>
        <displayFormat>ORDER_ITEM_I-{0000000}</displayFormat>
        <label>Pizza Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Order_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CalculateOrderItemCostTriggerHandler.cls
public class CalculateOrderItemCostTriggerHandler {
    public static void process(List<Pizza_Order_Item__c> records) {
        for(Pizza_Order_Item__c item : records)
        {
            Pizza__c pizza = [SELECT Id, Cost__c FROM Pizza__c WHERE Id = :item.Pizza__c];
            Pizza_Base__c pizzaBase = [SELECT Id, Cost__c FROM Pizza_Base__c WHERE Id = :item.Pizza_Base__c];
            item.Cost__c = 0;
            item.Cost__c += pizza.Cost__c;
            item.Cost__c += pizzaBase.Cost__c;
            item.Cost__c *= item.Count__c;
        }
    }
}