objects/Pizza__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Custom</label>
        <type>Checkbox</type>
    </fields>
    <label>Pizza</label>
    <nameField>
        <label>Pizza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Ingredient</label>
    <nameField>
        <label>Pizza Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient_Item__c.object
<CustomObject>
    <fields>
        <fullName>Pizza_Ingredient__c</fullName>
        <label>Pizza_Ingredient</label>
        <referenceTo>Pizza_Ingredient__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Ingredient_Item</label>
    <nameField>
        <displayFormat>Ingredient_I-{0000000}</displayFormat>
        <label>Pizza Ingredient Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Ingredient_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PizzaWrapperTest.cls
@isTest
private class PizzaWrapperTest {

	@isTest static void test_method_one() {
		Contact customer = new Contact(
			FirstName = 'Test',
			LastName = 'Test'
		);
		insert customer;

		Pizza_Ingredient__c ingr1 = new Pizza_Ingredient__c(
            Cost__c = 5,
			Name = 'Test ing1'
		);
		insert ingr1;
		
		Pizza_Ingredient__c ingr2 = new Pizza_Ingredient__c(
            Cost__c = 10,
			Name = 'Test ing2'
		);
		insert ingr2;

        Pizza__c pizza = new Pizza__c(
			Name = 'Test pizza'
		);
		insert pizza;
		
		Pizza_Ingredient_Item__c item1 = new Pizza_Ingredient_Item__c(
			Pizza_Ingredient__c = ingr1.Id,
			Pizza__c = pizza.Id
		);
		insert item1;
		
		Pizza_Ingredient_Item__c item2 = new Pizza_Ingredient_Item__c(
			Pizza_Ingredient__c = ingr2.Id,
			Pizza__c = pizza.Id
		);
		insert item2;
        
        
		Test.startTest();
        
        PizzaWrapper wrapper = new PizzaWrapper(pizza);
		System.assert(pizza.Cost__c == wrapper.cost);
        System.assert(pizza.Is_Custom__c == wrapper.isCustom);
        System.assert(pizza.Id == wrapper.detailId);
        System.assert('Test ing1 Test ing2 ' == wrapper.ingredients);
        System.assertNotEquals(wrapper,null);
		Test.stopTest();
	}

}