objects/Pizza__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza</label>
    <nameField>
        <label>Pizza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Ingredient</label>
    <nameField>
        <label>Pizza Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient_Item__c.object
<CustomObject>
    <fields>
        <fullName>Pizza_Ingredient__c</fullName>
        <label>Pizza_Ingredient</label>
        <referenceTo>Pizza_Ingredient__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Ingredient_Item</label>
    <nameField>
        <displayFormat>Ingredient_I-{0000000}</displayFormat>
        <label>Pizza Ingredient Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Ingredient_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdatePizzaCostTriggerHandler.cls
public class UpdatePizzaCostTriggerHandler {
    public static void process(List<Pizza_Ingredient_Item__c> records, List<Pizza_Ingredient_Item__c> old, Boolean isDelete) {
        if(isDelete)
        {
            for(Pizza_Ingredient_Item__c item : old)
            {
                Pizza__c temp = [SELECT Id,Cost__c FROM Pizza__c WHERE Id = :item.Pizza__c];
                Pizza_Ingredient__c ing = [SELECT Id,Cost__c FROM Pizza_Ingredient__c WHERE Id = :item.Pizza_Ingredient__c];
                temp.Cost__c -= ing.Cost__c;
                update temp;
            }
        }
        else
        {
            for(Pizza_Ingredient_Item__c item : records)
            {
                Pizza__c temp = [SELECT Id,Cost__c FROM Pizza__c WHERE Id = :item.Pizza__c];
                Pizza_Ingredient__c ing = [SELECT Id,Cost__c FROM Pizza_Ingredient__c WHERE Id = :item.Pizza_Ingredient__c];
                if(temp.Cost__c == null) temp.Cost__c = 0;
                temp.Cost__c += ing.Cost__c;
                update temp;
            }
        }
    }
}