objects/Pizza__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pizza</relationshipLabel>
        <relationshipName>Pizza</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Custom</label>
        <type>Checkbox</type>
    </fields>
    <label>Pizza</label>
    <nameField>
        <label>Pizza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Base__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Base</label>
    <nameField>
        <label>Pizza Base Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Bases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Ingredient</label>
    <nameField>
        <label>Pizza Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient_Item__c.object
<CustomObject>
    <fields>
        <fullName>Pizza_Ingredient__c</fullName>
        <label>Pizza_Ingredient</label>
        <referenceTo>Pizza_Ingredient__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Ingredient_Item</label>
    <nameField>
        <displayFormat>Ingredient_I-{0000000}</displayFormat>
        <label>Pizza Ingredient Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Ingredient_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pizza_Order__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <summarizedField>Pizza_Order_Item__c.Cost__c</summarizedField>
        <summaryForeignKey>Pizza_Order_Item__c.Pizza_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pizza_Orders</relationshipLabel>
        <relationshipName>Pizza_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pizza_Order</label>
    <nameField>
        <displayFormat>Order_I-{0000000}</displayFormat>
        <label>Pizza Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pizza_Base__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pizza_Base</label>
        <referenceTo>Pizza_Base__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pizza_Order__c</fullName>
        <label>Pizza_Order</label>
        <referenceTo>Pizza_Order__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Order_Item</label>
    <nameField>
        <displayFormat>ORDER_ITEM_I-{0000000}</displayFormat>
        <label>Pizza Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Order_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PizzaController.cls
public with sharing class PizzaController {
    
    public Id currentContactId { get; set; }
    public List<PizzaWrapper> pizzaWrapperList { get; set; }
    public List<PizzaIngredientWrapper> pizzaIngredientWrapperList { get; set; }
    public String customPizzaName { get; set; }
    
    public List<SelectOption> getBaseOptions(){
        
        List<SelectOption> baseOptions = new List<SelectOption>();
        List<Pizza_Base__c> baseItems = [SELECT Id, Name, Cost__c FROM Pizza_Base__c];
        for(Pizza_Base__c base : baseItems)
        {
            baseOptions.add(new SelectOption(base.Id, base.Name));
        }
        return baseOptions;
    }
    
    public List<SelectOption> getAmountOptions(){
        
        List<SelectOption> amountOptions = new List<SelectOption>();
        for(Integer i = 1; i < 6; i++)
        {
            amountOptions.add(new SelectOption(string.valueof(i), string.valueof(i)));
        }
        return amountOptions;
    }
    
    public PizzaController() {
        
        User currentUser = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
        currentContactId = currentUser.ContactId;
        
        pizzaIngredientWrapperList = new List<PizzaIngredientWrapper>();
        List<Pizza_Ingredient__c> pizzaIngredientItems = [SELECT Id, Name FROM Pizza_Ingredient__c];
        for(Pizza_Ingredient__c item : pizzaIngredientItems)
        {
            pizzaIngredientWrapperList.add( new pizzaIngredientWrapper(item));
        }
        retrievePizzaData();
        
        
        
    }
    
    public void addToOrder(){
        
        List<Pizza_Order_Item__c> temp = new List<Pizza_Order_Item__c>();
        for(PizzaWrapper pizza : pizzaWrapperList)
        {
            if(pizza.isChecked)
            {
                temp.add( new Pizza_Order_Item__c(
                    Pizza_Base__c = pizza.base,
                    Pizza__c = pizza.detailId,
                    Pizza_Order__c = null,
                    Count__c = Integer.valueOf(pizza.amount)
                ));
            }
        }
        if(!temp.isEmpty())
        {
            Pizza_Order__c newOrder = new Pizza_Order__c(
                Customer__c = currentContactId
                );
            insert newOrder;
            for(Pizza_Order_Item__c item : temp)
            {
                item.Pizza_Order__c = newOrder.Id;
            }
            insert temp;
            sendReport(newOrder);
            
        }
        
    }
    
    public void retrievePizzaData() {
		
	    pizzaWrapperList = new List<PizzaWrapper>();
        List <Pizza__c> pizzaItems = [SELECT Id, Name, Cost__c, Customer__c FROM Pizza__c WHERE Pizza__c.Customer__c = :currentContactId OR Pizza__c.Is_Custom__c = false ];
        for(Pizza__c pizza : pizzaItems)
        {
            pizzaWrapperList.add( new PizzaWrapper(pizza));
        }
		
	}
    
    public void addCustomPizza(){
        
        List<Pizza_Ingredient_Item__c> ingrList = new List<Pizza_Ingredient_Item__c>();
        for(PizzaIngredientWrapper ingr : pizzaIngredientWrapperList)
        {
            if(ingr.isChecked)
            {
                Pizza_Ingredient_Item__c temp = new Pizza_Ingredient_Item__c(
                    Pizza_Ingredient__c = ingr.detailId
                );
                ingrList.add(temp);
            }
            
        }
        if(!ingrList.isEmpty())
        {
            Pizza__c newPizza = new Pizza__c(
                Name = customPizzaName,
                Is_Custom__c = true,
                Customer__c = currentContactId
                );
            insert newPizza;
            for(Pizza_Ingredient_Item__c ingr : ingrList)
            {
                ingr.Pizza__c = newPizza.Id;
            }
            insert ingrList;
        }
        retrievePizzaData();
    }
    private void sendReport(Pizza_Order__c newOrder){
        User temp = [SELECT Id, ContactId, Email, FirstName, LastName FROM User WHERE Id = :UserInfo.getUserId()];
        //Contact temp = [SELECT Id, Email, FirstName, LastName FROM Contact WHERE Id = :currentContactId];
        Decimal sum = 0;
        String mailReport = 'Hello, ';
        mailReport += temp.FirstName;
        mailReport += ' ';
        mailReport += temp.LastName;
        mailReport += '!\nYour order:\n';
        List<Pizza_Order_Item__c> items = [SELECT Id, Pizza__c, Pizza__r.Name, Count__c, Pizza_Base__c, Pizza_Base__r.Name,Pizza_Order__c, Cost__c 
                                            FROM Pizza_Order_Item__c 
                                            WHERE Pizza_Order_Item__c.Pizza_Order__c = :newOrder.Id];
        for(Pizza_Order_Item__c item : items)
        {
            mailReport += item.Pizza__r.Name;
            mailReport += '  ';
            mailReport += item.Pizza_Base__r.Name;
            mailReport += '  x';
            mailReport += String.valueOf(item.Count__c);
            mailReport += '  ';
            mailReport += String.valueOf(item.Cost__c);
            mailReport += '$\n';
            sum += item.Cost__c;
        }
        mailReport += 'Summary: ';
        //mailReport += String.valueOf(newOrder.Cost__c);
        mailReport += String.valueOf(sum);
        mailReport += '$\n';
        AwesomeNotifyHelper.notify(/*'londonversusall@gmail.com'*/temp.Email, mailReport, null);
    }
}