objects/Pizza__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pizza</relationshipLabel>
        <relationshipName>Pizza</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Custom</label>
        <type>Checkbox</type>
    </fields>
    <label>Pizza</label>
    <nameField>
        <label>Pizza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Base__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Base</label>
    <nameField>
        <label>Pizza Base Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Bases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Ingredient</label>
    <nameField>
        <label>Pizza Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient_Item__c.object
<CustomObject>
    <fields>
        <fullName>Pizza_Ingredient__c</fullName>
        <label>Pizza_Ingredient</label>
        <referenceTo>Pizza_Ingredient__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Ingredient_Item</label>
    <nameField>
        <displayFormat>Ingredient_I-{0000000}</displayFormat>
        <label>Pizza Ingredient Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Ingredient_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pizza_Order__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <summarizedField>Pizza_Order_Item__c.Cost__c</summarizedField>
        <summaryForeignKey>Pizza_Order_Item__c.Pizza_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pizza_Orders</relationshipLabel>
        <relationshipName>Pizza_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pizza_Order</label>
    <nameField>
        <displayFormat>Order_I-{0000000}</displayFormat>
        <label>Pizza Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pizza_Base__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pizza_Base</label>
        <referenceTo>Pizza_Base__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pizza_Order__c</fullName>
        <label>Pizza_Order</label>
        <referenceTo>Pizza_Order__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Order_Items</relationshipLabel>
        <relationshipName>Pizza_Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Order_Item</label>
    <nameField>
        <displayFormat>ORDER_ITEM_I-{0000000}</displayFormat>
        <label>Pizza Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Order_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PizzaControllerTest.cls
@isTest
private class PizzaControllerTest {

	@isTest static void test_method_one() {
		PizzaController controller = new PizzaController();
        
        Contact customer = new Contact(
			FirstName = 'Test',
			LastName = 'Test'
		);
		insert customer;
	
		Pizza_Base__c item1 = new Pizza_Base__c(
			Name = 'base1'
		);
		insert item1;
		
		Pizza_Base__c item2 = new Pizza_Base__c(
			Name = 'base2'
		);
		insert item2;
        
        List<SelectOption> baseOptions = new List<SelectOption>();
        baseOptions.add(new SelectOption(item1.Id, item1.Name));
        baseOptions.add(new SelectOption(item2.Id, item2.Name));
        
		Test.startTest();
        System.assertEquals(controller.getBaseOptions(), baseOptions);
        Test.stopTest();
	}
    @isTest static void test_method_two() {
        
		PizzaController controller = new PizzaController();
        
        List<SelectOption> aOptions = new List<SelectOption>();
        aOptions.add(new SelectOption('1','1'));
        aOptions.add(new SelectOption('2','2'));
        aOptions.add(new SelectOption('3','3'));
        aOptions.add(new SelectOption('4','4'));
        aOptions.add(new SelectOption('5','5'));
		
		Test.startTest();
        System.assertEquals(controller.getAmountOptions(), aOptions);
		Test.stopTest();

	}
	@isTest static void test_method_three() {
	    
	    Contact customer = new Contact(
			FirstName = 'Test',
			LastName = 'Test'
		);
		insert customer;
	
		PizzaController controller = new PizzaController();
        
        Pizza__c pizza = new Pizza__c(
			Cost__c = 5,
			Name = 'Test pizza'
			
		);
		insert pizza;
		
		Pizza__c pizza2 = new Pizza__c(
			Cost__c = 10,
			Name = 'Test pizza2'
		);
		insert pizza2;

		Pizza_Base__c base = new Pizza_Base__c(
			Cost__c = 1,
			Name = 'Test base'
		);
		insert base;

		Pizza_Order__c testOrder = new Pizza_Order__c(
			Customer__c = customer.Id
		);
		insert testOrder;
        
        
		Test.startTest();

		Pizza_Order_Item__c orderItem1 = new Pizza_Order_Item__c(
			Pizza__c = pizza.Id,
			Pizza_Base__c = base.Id,
			Pizza_Order__c = testOrder.Id,
			Count__c = 1
		);
		insert orderItem1;
		
		Pizza_Order_Item__c orderItem2 = new Pizza_Order_Item__c(
			Pizza__c = pizza2.Id,
			Pizza_Base__c = base.Id,
			Pizza_Order__c = testOrder.Id,
			Count__c = 1
		);
		insert orderItem2;
		update testOrder;
		
		List<PizzaWrapper> pw = new List<PizzaWrapper>();
		pw.add(new PizzaWrapper(pizza));
		pw.add(new PizzaWrapper(pizza2));
		pw[0].base = base.Id;
		pw[1].base = base.Id;
		pw[0].isChecked = true;
		pw[1].isChecked = true;
		pw[0].amount = '1';
		pw[1].amount = '1';
		controller.pizzaWrapperList = pw;
		controller.currentContactId = customer.Id;
		controller.addToOrder();
		
		Pizza_Order__c temp = [SELECT Id,  Customer__c, Cost__c FROM Pizza_Order__c ORDER BY CreatedDate desc limit 1];
		System.assert(temp.Customer__c == testOrder.Customer__c);
        System.assert(temp.Cost__c == 17);
		
		Test.stopTest();
}
    @isTest static void test_method_four() {
	    
	    Contact customer = new Contact(
			FirstName = 'Test',
			LastName = 'Test'
		);
		insert customer;
		
		PizzaController controller = new PizzaController();
        
      
        Pizza__c pizza = new Pizza__c(
			Name = 'pizza',
			Customer__c = customer.Id,
			Is_Custom__c = true
			
		);
		insert pizza;
		
		Pizza_Ingredient__c ingr = new Pizza_Ingredient__c(
            Cost__c = 5,
			Name = 'Test ing1'
		);
		insert ingr;
		
		Pizza_Ingredient_Item__c ingrItem = new Pizza_Ingredient_Item__c(
            Pizza_Ingredient__c = ingr.Id,
            Pizza__c = pizza.Id
		);
		insert ingrItem;
        
        Pizza_Ingredient_Item__c ingrItem2 = new Pizza_Ingredient_Item__c(
            Pizza_Ingredient__c = ingr.Id,
            Pizza__c = pizza.Id
		);
		insert ingrItem2;
        
		Test.startTest();

		List<PizzaIngredientWrapper> pw = new List<PizzaIngredientWrapper>();
		pw.add(new PizzaIngredientWrapper(ingr));
		pw.add(new PizzaIngredientWrapper(ingr));
		pw[0].isChecked = true;
		pw[1].isChecked = true;

		controller.pizzaIngredientWrapperList = pw;
		controller.currentContactId = customer.Id;
		controller.addCustomPizza();
		controller.customPizzaName = 'pizza';
		
		Pizza__c temp = [SELECT Id, Customer__c, Cost__c, Is_Custom__c FROM Pizza__c ORDER BY CreatedDate desc limit 1];
		System.assert(temp.Customer__c == customer.Id);
        System.assert(temp.Cost__c == 10);
		System.assert(temp.Is_Custom__c == true);

		Test.stopTest();
    }
}