objects/Pizza__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pizza</relationshipLabel>
        <relationshipName>Pizza</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pizza</label>
    <nameField>
        <label>Pizza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pizza_Ingredient</label>
    <nameField>
        <label>Pizza Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pizza_Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pizza_Ingredient_Item__c.object
<CustomObject>
    <fields>
        <fullName>Pizza_Ingredient__c</fullName>
        <label>Pizza_Ingredient</label>
        <referenceTo>Pizza_Ingredient__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pizza__c</fullName>
        <label>Pizza</label>
        <referenceTo>Pizza__c</referenceTo>
        <relationshipLabel>Pizza_Ingredient_Items</relationshipLabel>
        <relationshipName>Pizza_Ingredient_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pizza_Ingredient_Item</label>
    <nameField>
        <displayFormat>Ingredient_I-{0000000}</displayFormat>
        <label>Pizza Ingredient Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza_Ingredient_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PizzaWrapper.cls
public class PizzaWrapper {

	public Id detailId { get; set; }
	public String name { get; set; }
	public String ingredients { get; set; }
	public Boolean isChecked { get; set; }
	public Id base { get; set; }
	public String amount { get; set; }
	public Boolean isCustom { get; set; }
	public Double cost { get; set; }
	public PizzaWrapper() {

	}

	public PizzaWrapper(Pizza__c pizza ) {
		detailId = pizza.Id;
		name = pizza.Name;
		isChecked = false;
		cost = pizza.Cost__c;
		isCustom = pizza.Customer__c == null ? false : true;
		ingredients = '';
		List<Pizza_Ingredient_Item__c> ingr = [SELECT Id, Name,Pizza_Ingredient__c FROM Pizza_Ingredient_Item__c WHERE Pizza__c =: pizza.Id ];
		for(Pizza_Ingredient_Item__c i : ingr)
		{
		    Pizza_Ingredient__c temp = [SELECT Id,Name FROM Pizza_Ingredient__c WHERE Id =: i.Pizza_Ingredient__c ];
		    ingredients += temp.Name;
		    ingredients += ' ';
		}
	}

	

}